### ISSUE TITLE
`668755_2023-08-29` surface channel upload

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_lims#15]
This session had apparently had a main recording and two surface recordings.

Times, from xml files: 
1. `29 Aug 2023 11:18:18` (extra)
2. `29 Aug 2023 13:11:37` (main session)
3. `29 Aug 2023 15:10:27` (surface channels)

Ethan suspects 3 is the correct surface channel rec (but it seems a long time
after the first, and 4 hours after the main recording started - is there any
history of what happened?)

--> 3 is correct. 2 is the main session

All three are still on the Isilon. 
Ethan renamed 1 and 3:
1. `DRpilot_668755_20230829_surface_channels (1)` -> `DRpilot_668755_20230829_surface_channels`
3. `DRpilot_668755_20230829_surface_channels` -> `DRpilot_668755_20230829_surface_channels (2)`

Only 1 and 2 are on S3:
- [x] make sure 3 is correct, 1 incorrect: 
- [x] delete 1 on S3
- [x] upload 3

**Comment by egmcbride** [comment]
Looking at the file folders on the Isilon, recording 2 is actually the main session, and recording 1 must have been an accidental early run of the surface channels recording, so recording 3 is the true surface channels recording.

**Comment by bjhardcastle** [comment]
Thanks Ethan.

So it's 1 that needs deleting on S3 then - I'll update the task list
